
default: help

debug: 
		ant debug

release:
		ant release
		
clean:
		ant clean

compile:
		ant compile

install:
		ant install

uninstall:
		ant uninstall


help:
		@echo ""
		@echo "Make targets available:"
		@echo ""
		@echo "  make clean     - Removes build files"
		@echo "  make compile   - Compiles java files"
		@echo "  make debug     - Builds the app and signs it with debug key"
		@echo "  make release   - Builds the app and signs it with release key"
		@echo "  make install   - Installs the app in a running emulator"
		@echo "  make uninstall - Uninstall from a running emulator"
		@echo ""


